// src/lib/presets.ts

import type { Rival } from "@/types";

export const MASTERMINDS: Rival[] = [
  {
    id: "mastermind_ayanokoji",
    rank: 0,
    name: "Kiyotaka Ayanokoji",
    gpa: 6.0,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "WHITE_ROOM",
    bio: "Product of the White Room. Perfect in every measurable category. He does not compete. He observes. The gap between him and everyone else is not talent — it is design.",
    traits: ["Genius", "Manipulator", "Hidden"],
    avatar: "🧊",
  },
  {
    id: "mastermind_sora_shiro",
    rank: 0,
    name: "Sora & Shiro",
    gpa: 6.0,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "NO_GAME_NO_LIFE",
    bio: "Blank. Undefeated across 280 worlds. They do not play games. They solve them. Together they are the theoretical maximum of human coordination.",
    traits: ["Genius", "Unbeatable", "Symbiotic"],
    avatar: "👑",
  },
  {
    id: "mastermind_kaiser",
    rank: 0,
    name: "Michael Kaiser",
    gpa: 5.98,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "BLUE_LOCK",
    bio: "New Generation World Eleven. His Kaiser Impact is the fastest direct shot ever recorded. He does not ask for the ball. The world adjusts to him.",
    traits: ["Striker", "Egoist", "Perfectionist"],
    avatar: "⚡",
  },
  {
    id: "mastermind_isagi",
    rank: 0,
    name: "Isagi Yoichi",
    gpa: 5.95,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "BLUE_LOCK",
    bio: "Entered Blue Lock as the weakest. Devoured everyone above him. His weapon is vision — he sees the play before it happens and positions himself where the goal will be.",
    traits: ["Adaptable", "Egoist", "Spatial"],
    avatar: "🎯",
  },
  {
    id: "mastermind_rin",
    rank: 0,
    name: "Rin Itoshi",
    gpa: 5.92,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "BLUE_LOCK",
    bio: "The prodigy of destruction. He does not score to win. He scores to annihilate. Every shot is calculated to break the opponent's will, not just the net.",
    traits: ["Prodigy", "Destruction", "Precision"],
    avatar: "🔥",
  },
  {
    id: "mastermind_light",
    rank: 0,
    name: "Light Yagami",
    gpa: 5.9,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "DEATH_NOTE",
    bio: "Number one student in Japan. Perfect scores on every exam. Then he found a notebook and decided the world needed a god. That is the distance between talent and madness.",
    traits: ["Genius", "Ambitious", "God Complex"],
    avatar: "📓",
  },
  {
    id: "mastermind_l",
    rank: 0,
    name: "L Lawliet",
    gpa: 5.9,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "DEATH_NOTE",
    bio: "World's greatest detective. Solved cases that entire agencies could not. Operates on a frequency no one else can hear. Eats sugar like it is oxygen.",
    traits: ["Detective", "Unorthodox", "Analytical"],
    avatar: "🍰",
  },
  {
    id: "mastermind_lelouch",
    rank: 0,
    name: "Lelouch vi Britannia",
    gpa: 5.88,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "CODE_GEASS",
    bio: "Exiled prince who overthrew the world's largest empire with strategy alone. He saw ten moves ahead and sacrificed everything to reach the future he designed.",
    traits: ["Strategist", "Revolutionary", "Sacrificial"],
    avatar: "♟",
  },
  {
    id: "mastermind_itachi",
    rank: 0,
    name: "Itachi Uchiha",
    gpa: 5.85,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "NARUTO",
    bio: "Massacred his entire clan to prevent a civil war. Carried the hatred of the world alone. Died with a smile. Strength without ego is what makes him unreachable.",
    traits: ["Sacrifice", "Genjutsu", "Burdened"],
    avatar: "🦅",
  },
  {
    id: "mastermind_shikamaru",
    rank: 0,
    name: "Shikamaru Nara",
    gpa: 5.82,
    isConfirmed: true,
    type: "SYNTHETIC",
    velocity: 0.0,
    volatility: 0.0,
    origin: "NARUTO",
    bio: "IQ over 200. Predicts 200 moves ahead while calling everything troublesome. His laziness is a mask. His mind is a machine that never stops running.",
    traits: ["Strategist", "Lazy Genius", "Tactical"],
    avatar: "☁",
  },
];
